name: testing 
on:
  push:
    branches:
      - main

env:
  DOCKER_USER: adysh97

jobs:
  power-docker-example:
    runs-on: ubuntu-latest-ppc64le
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install docker
        run: |
          sudo apt update -qqy 
          sudo apt install docker.io  make -qqy 
          sudo systemctl start docker 
          sudo usermod -aG docker  ubuntu
          sudo newgrp docker 


      - name: Login to DockerHub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: build docker image 
        run: |
            docker build .
